### ISSUE TITLE
Theme Pull Quote layout

### ISSUE THREAD

**Issue by c9rgreen** [ualibraries/500#16]
![screen shot 2017-07-18 at 11 41 56 am](https://user-images.githubusercontent.com/868735/28333864-29fa3670-6bae-11e7-96b6-c25dae84c0a6.png)

**Comment by liquid06** [comment]
I wasn't able to find an obvious way in Omeka's theme documentation to de-queue a CSS file that's added by a plugin, so for now I added overrides for the pull quote styling. This branch also includes the work in progress from #6 .
