### ISSUE TITLE
Add Universal Viewer display logic and order content for item page

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#18]
- [x] Conditionally include the Universal Viewer at the top of the page based on the item type (set in Redmine issue 9760)
- [x] If the Universal Viewer is included, don't display all the files separate from that
- [x] If there's no UV, display the item files, then item metadata, and last citation and collection
- [x] Remove the "Dublin Core" heading from the metadata section
- [x] Make sure the exhibit header and navigation display and work correctly, so  user could navigate to another section of the exhibit from the item page

**Comment by caosborne89** [comment]
The navigation is showing up on the item show page, though it's not working at the moment because the header is being worked on.

**Comment by caosborne89** [comment]
For the Omeka Build project, I'm putting these changes on branch uv_item_display branch

**Comment by simpsonw** [comment]
This all looks good to me.  I've merged the branch in Omeka Build and tagged and deployed it.
