### ISSUE TITLE
Improve file metadata display

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#19]
Our Omeka theme currently does not display metadata associated with the file and the alt-text and title element both contain the filename.

We want to at least display the title of each file and improve the alt-text so that it includes the contents of the title field and the contents of the date field separated by a comma.

We don't want too much of the file metadata to show up on the item page. The title is OK and helpful, but the rest, if it is present, should be hidden by way of:

- Change the link so when the user clicks the file they see the file's page rather than the original image
- Add the metadata on the item, but hide it behind a hover effect or an expand/collapse UI control

Things to do:

- [ ] Display the title element from the file metadata and hide other metadata behind another user interaction
- [x] Change the alt text to include (if available) the file's title and date. `[dc:title], [dc:date]`
- [x] Remove the title attribute from the image because it would be redundant

**Comment by liquid06** [comment]
Here's what I've learned so far:

- Core Omeka themes don't display file metadata by default, it seems this feature isn't widely used
- It is possible to access the file metadata from the theme - [here's the example I followed](https://forum.omeka.org/t/how-to-display-metadata-about-uploaded-file-s-in-my-theme/2191)
- [Metadata](http://omeka.readthedocs.io/en/latest/Reference/libraries/globals/metadata.html) allows printing field values individually
- Files get their own pages - using a [special link_to](http://omeka.readthedocs.io/en/latest/Reference/libraries/globals/link_to_file_show.html) on the item page can let the user see file pages 
- The theme could override how the file pages look by overriding [this template](https://github.com/omeka/Omeka/blob/master/application/views/scripts/files/show.php)

**Comment by simpsonw** [comment]
It looks like the Dublin Core information for the File is already showing up on the Item page:

![file_dublin_core](https://user-images.githubusercontent.com/10437788/28590176-103b205e-7136-11e7-8260-f03e48046ab7.png)

Given that there's already a lot of work being done in #17 regarding reorganizing the Item page, I'm thinking it might make sense to close this task, merge the feature branch and do any remaining work on that ticket to avoid merge conflicts, duplicated work, etc.  What do others think? @caosborne89 @liquid06 @cg433n

**Comment by liquid06** [comment]
Yes, right on. Andy and Christopher and I talked about this earlier and we merged the branch for 19 into the branch for 17. Christopher is continuing that work on #17 so I think we can close this.
