### ISSUE TITLE
Typography notes

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#23]
_design review notes_

When we looked at the text it seemed blurry or too bold. There was a significant difference in the rendering in chrome and safari, so much so that it looked like it might be loading the wrong font.

The original comp included 25 tracking. Letterspacing isn't usually recommended on the web for the sake of readability, but if the font still seems overly bold it might need an adjustment.

This comparison is chrome/linux vs macos/safari:
![image](https://user-images.githubusercontent.com/460005/28739226-184334e2-73ae-11e7-8f10-86273ef83758.png)

**Comment by c9rgreen** [comment]
Wontfix.
