### ISSUE TITLE
Update exhibit menu styles

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#24]
- [x] Try using a smaller or repeating background
- [x] Menu background should occupy the full browser viewport height
- [x] Font size should be the same as `Browse all items` link
- [x] The rest of the body should be darkened when the menu is opened

**Comment by c9rgreen** [comment]
After talking about it more, here is what we have decided to do:

- Try using a smaller or repeating background
- Menu background should occupy the full browser viewport height
- Font size should be the same as `Browse all items` link
