### ISSUE TITLE
Update homepage image styles

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#25]
- [x] Reduce the width of the homepage image (upload a new asset in theme configuration)
- [x] Make the fade to transparent gradient border around the homepage image more narrow (new asset)
- [x] Reduce spacing beneath homepage image

**Comment by liquid06** [comment]
During standup today, Molly noted that the content winds up pretty far down the page. Though how much can appear depends on the device you're using, tightening the vertical space occupied by the header and the homepage image would help with this.

**Comment by c9rgreen** [comment]
After talking about it more, here is what we decided to do:

- Reduce the width of the homepage image
- Make the fade to transparent gradient border around the homepage image more narrow
- Reduce spacing beneath homepage image

**Comment by c9rgreen** [comment]
There is currently no spacing beneath the image.

![screen shot 2017-08-01 at 10 17 04 am](https://user-images.githubusercontent.com/868735/28837713-a70f377e-76a2-11e7-9dd4-e40c60f75a69.png)
