### ISSUE TITLE
Always show previous and next arrows in Universal Viewer

### ISSUE THREAD

**Issue by liquid06** [ualibraries/500#32]
When reviewing the Universal Viewer display in the 500 theme, we noticed that the previous and next arrows on the side of the viewer only appear on hover. Is there a configuration option to make them display all the time?

**Comment by c9rgreen** [comment]
![screen shot 2017-08-03 at 12 39 59 pm](https://user-images.githubusercontent.com/868735/28940674-60a63bf8-784a-11e7-8773-33743e2693a2.png)

**Comment by c9rgreen** [comment]
It looks like this is controlled by `modules.seadragonCenterPanel.options.autoHideControls` in `universal-viewer/config.json`.
