### ISSUE TITLE
Make the theme

### ISSUE THREAD

**Issue by RuiQiDev** [ualibraries/500#5]
Working on the css, yeah~~
![reformation-homepage-v2](https://user-images.githubusercontent.com/19802273/28175515-511c3888-67a9-11e7-94e0-0c8b16921530.jpg)
![reformation-content-page](https://user-images.githubusercontent.com/19802273/28175628-a0979fce-67a9-11e7-9fc5-447559dd7b66.jpg)
![reformation-nav-v2](https://user-images.githubusercontent.com/19802273/28175635-a3fddb4c-67a9-11e7-8289-b06b19252de2.png)

**Comment by c9rgreen** [comment]
Declined in favor of a more granular task breakdown.
