### ISSUE TITLE
Theme header component

### ISSUE THREAD

**Issue by c9rgreen** [ualibraries/500#6]
https://projects.invisionapp.com/d/main#/console/11557980/244111641/preview

![screen shot 2017-07-18 at 11 25 57 am](https://user-images.githubusercontent.com/868735/28333138-e5f461c8-6bab-11e7-8426-5d4cc8e933d9.png)

**Comment by liquid06** [comment]
testing...

**Comment by liquid06** [comment]
I'm getting the hang of working with this. (I ran into a couple of errors initially as the theme uploads directory had incorrect permissions in my local build.) By default I tend to write styles considering small screens first, then making modifications for larger screens - here is the state I got to.

![image](https://user-images.githubusercontent.com/460005/28346151-ed34d2fa-6be3-11e7-864f-ed235808d532.png)

For anyone else taking a look at this ticket or other theme tickets, Christopher and I talked about these conventions in person:

- We're including the CSS from boilerplate in our base stylesheet and adding our global modifications in the `Author's custom styles` section. This way we get nice print stylesheets and helpful utility styling.
- We're not including a grid system for this project, but instead adding layout as it's needed for separate tasks; we wouldn't get much benefit (That said, I did add layout as a separate partial but I'm not sure if that division is totally necessary.)
- We're preferring classes over IDs for styling, but we won't bend over backwards to change the markup if it would take a lot more time to do so.

**Comment by liquid06** [comment]
The next step for this ticket is to add drop shadows, the menu button texture, and other special texture or visual treatment in the header area. It would probably be best to implement the collapsible menu next and include the header and the menu when doing design review.

status:
![image](https://user-images.githubusercontent.com/460005/28394048-43493576-6c9f-11e7-9f78-bcbb3f8ef240.png)
